# Generated by Django 4.1.7 on 2023-05-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Genre')),
                ('description', models.TextField(verbose_name='Description')),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Zhanr',
                'verbose_name_plural': 'Zhanry',
            },
        ),
        migrations.AlterModelOptions(
            name='films',
            options={'verbose_name': 'Film', 'verbose_name_plural': 'Films'},
        ),
        migrations.RemoveField(
            model_name='films',
            name='date',
        ),
        migrations.AddField(
            model_name='films',
            name='image',
            field=models.ImageField(default='', upload_to='static/img', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='films',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Nazvanie'),
        ),
        migrations.AddField(
            model_name='films',
            name='genres',
            field=models.ManyToManyField(to='main.genre', verbose_name='Zhanr'),
        ),
    ]
