# Generated by Django 4.1.7 on 2023-05-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_genre_alter_films_options_remove_films_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='image',
            field=models.ImageField(default='', upload_to='main/static/img', verbose_name='image'),
        ),
    ]
